### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by MiranoVerhoef** [BrytonSalisbury/mesh-mini#2]
Would you be able to make this into a docker?

That'd be amazing for management.

**Comment by BrytonSalisbury** [comment]
Readme has been updated with the published Docker image, and instructions of building the Docker image from source.

**Comment by BrytonSalisbury** [comment]
Readme has been updated with Docker image instructions. Image has been published here - https://hub.docker.com/r/brytonsalisbury/mesh-mini
