### ISSUE TITLE
Version of MeshCommander

### ISSUE THREAD

**Issue by MiranoVerhoef** [BrytonSalisbury/mesh-mini#4]
Hello,

It seems to be that when i launched this i'm pressented with version: 0.9.3
<img width="249" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/67699857/54bfd1ad-ba9b-48af-9e25-19c50d6e8f80">

For my connection i need to use either 0.9.5 or 0.9.6 (Latest release)

Can you update the bundle within for the new version of Meshcommander?

**Comment by BrytonSalisbury** [comment]
@MiranoVerhoef, can you send a larger image of the URL you're accessing? This version is 0.9.5.

<img width="497" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/a8144d18-4630-429f-91e2-c979f44847ad">

**Comment by BrytonSalisbury** [comment]
@MiranoVerhoef, can you send a larger image of the URL you're accessing? This version is 0.9.5.

<img width="498" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/34047c3b-a28f-4597-91ff-ab05b88fef44">

**Comment by MiranoVerhoef** [comment]
Hello,

As seen below i've got it running in container manager on a synology nas:

<img width="765" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/67699857/f823235c-3e3b-4f30-a9f6-8a41a2465ac5">

When i go to the local IP i get the following:

<img width="565" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/67699857/b31b9fce-3361-40c3-aa6f-dbb869fd943a">

**Comment by BrytonSalisbury** [comment]
Got it, unfortunately the localised pages are all on 0.9.3 and have not been brought forward to 0.9.5.

The 0.9.5 features are available on the default.htm page, but not default-nl.htm.

<img width="343" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/adea9e29-d5f6-4673-ac3d-a5e459781d97">

It would require a significant amount of work to bring the localised versions forward to 0.9.5 and I don't find it's worth the effort to bring these forward.

**Comment by MiranoVerhoef** [comment]
Check. It redirected me to the dutch page but i rather use the english variant.

When i use meshcommander i get a certificate pop-up but on this it just says. "Session Timeout" whilst IP + Details are correct and copied from a working 0.9.6. it works on all clients except the mesh-mini variant! 

Hoping to get it working :)

**Comment by BrytonSalisbury** [comment]
Sorry but I'm not quite following, is this the timeout error you're talking about?

<img width="1072" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/77e56ca9-9628-41a9-b3db-a39fcb6d33da">

Could you also clarify what you mean when you say 'copied from a working 0.9.6' and 'it works on all clients except the mesh-mini variant'. Mesh-mini doesn't facilitate AMT, this is only used to access computers already running Intel AMT on them.

Feel free to reach out on Discord if that's more convenient for you, happy to help. My username is brigton.

**Comment by BrytonSalisbury** [comment]
After discussion over Discord, we found that the node version of meshcommander does not appear to support importing TLS certificates.

Workaround for this is a Docker image to host meshcmd, which supports importing TLS certificates.

https://github.com/BrytonSalisbury/meshcmd
https://hub.docker.com/r/brytonsalisbury/meshcmd

```docker pull brytonsalisbury/meshcmd```
```docker run -p 3000:3000 brytonsalisbury/meshcmd```
