### ISSUE TITLE
Feature Request: Store config on server rather than client PCs

### ISSUE THREAD

**Issue by CaptInsano** [BrytonSalisbury/mesh-mini#6]
Thanks so much for this project, it is brilliant.

Is it possible to have the config (list of added PCs) saved on the server running mesh-mini rather than the client PCs.

Situation:
I have mesh-mini (docker container) set up on a central server on-site but I often have to access it from different clients. I would rather protect the single instance of mesh-mini and its preserved config (complete list of added PC with passwords) behind a strong password with my reverse proxy/authelia rather than having to remember all the IPs/Auths/Passwords for my vPro PCs whenever I log in from a different client.

I hope I am making sense with this!

Thanks again for your work!

**Comment by BrytonSalisbury** [comment]
Hey @CaptInsano!

This sounds like a great addition. I think this would be fairly simple to implement backend but I just want to check with you if this would be an acceptable solution

<img width="1288" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/e3654326-52b9-42f5-bbe4-663b5eb2c0f5">

(ignore the paint mockup)

I can add 2 buttons which will allow you to push and pull from the remote computer list on the Host. It won't allow you to push and pull individual computers, but the computer list will exist as an entire package.

The computer list will exist on the Host likely in a plaintext JSON file which is something to be cautious about, but I can't prevent the computer list from existing in the local browser storage on the clients, there is too much logic connected to this.

Let me know if this solution would work for you and I can probably have this done in a day :)

**Comment by BrytonSalisbury** [comment]
Implemented!

<img width="1093" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/79612105-568c-4b44-8001-81d378ffc35d">

<img width="1144" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/999806ce-1d11-4e17-8412-2ed2432da8cb">

<img width="1144" alt="image" src="https://github.com/BrytonSalisbury/mesh-mini/assets/24764099/02875a7d-94a9-484b-8bcb-a02fe3cf1406">

Let me know if this solution works for you, and I will compile and update the .exe and Docker

**Comment by CaptInsano** [comment]
That looks brilliant!

I will test once a new docker container is ready to pull from dockerhub.

Where is the config JSON saved too? I will need to pass a volume to make it persistent.

Thanks so much again for your work on this!

**Comment by BrytonSalisbury** [comment]
@CaptInsano Latest version has now been pushed to brytonsalisbury/meshmini

The JSON is currently stored in the root folder of the application. The file path is /usr/src/app/computers.json.

I'm not very well versed in Docker so I'm not sure how volumes/persistence works. Let me know if there's anything you need changed to make this happen!

**Comment by CaptInsano** [comment]
I will test later!

One common convention in Docker is for applications to store config files in /config which can then be mounted to the host file system. Keeping it out of the application directory allows for future application/container updates without overwriting the config.

Can mesh-mini be started with an argument to specify config folder location?

**Comment by BrytonSalisbury** [comment]
I'll look into it tomorrow and get back to you!

**Comment by CaptInsano** [comment]
All working perfectly!

Really appreciate your work on this.
