### ISSUE TITLE
Time Out Error

### ISSUE THREAD

**Issue by parallelsys** [BrytonSalisbury/mesh-mini#8]
Seems that I am hitting some Time Out Error. Doing some research it seems is related to TLS, but cant seem to find the fix. Ideas?

Works fine when using a different version running as localhost.

**Comment by BrytonSalisbury** [comment]
Could you please confirm which version of mesh-mini you're using, and when/where you're receiving timeouts?

**Comment by BenJamesAndo** [comment]
I'm also facing this issue. Also based on research it seems more likely to occur with computers running versions of Intel ME 10 or below. I have Intel ME v9.1.0. I can access it directly via WebUI port 16992 but there is no WebUI TLS port 16993.

When I use Mesh-mini in Chrome it just says Loading... for about 20 seconds then displays Timeout Error. If I try in Firefox I get Timeout Error immediately after clicking Connect.
If I use MeshCommander on my Windows computer it connects fine to my computers with v9.1.0 both in Digest / TLS and Digest / None.
![image](https://github.com/user-attachments/assets/f7a76d36-a58e-4943-aafc-f81b067bda7c)

**Comment by BenJamesAndo** [comment]
I've got access to a computer with Intel ME v12.0.6 and mesh-mini works great. No connection issues. So I suppose it was in fact an issue with old versions of Intel ME such as v9.1.0.

**Comment by BrytonSalisbury** [comment]
Unfortunately the oldest version of Intel ME I can find across our network is > v11.x.x. 

I won't have the capacity to troubleshoot the issue here since I cannot replicate, and can only recommend to update firmware if possible.
